import type { NativePresentation } from "../components/pptx-values.js";
import type { CreativeDirection, SlideAgentConfig } from "../types/index.js";

export class ThemeManager {
  public apply(presentation: NativePresentation, config: SlideAgentConfig, title: string, direction?: CreativeDirection): void {
    presentation.defineLayout({
      name: "SLIDE_AGENT_WIDE",
      width: config.dimensions.width,
      height: config.dimensions.height,
    });
    presentation.layout = "SLIDE_AGENT_WIDE";
    presentation.author = "Slide Agent";
    presentation.company = "Slide Agent";
    presentation.subject = direction?.concept ?? "Editable presentation generated by Slide Agent";
    presentation.title = title;
    presentation.revision = "1";
    presentation.theme = {
      headFontFace: config.fonts.heading,
      bodyFontFace: config.fonts.body,
    };
  }
}
