#!/usr/bin/env node
// Renders SKILL.md and the reference docs from the authoring contract, so the
// prose an agent reads and the schemas the engine enforces cannot drift apart.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Imported from source, not from dist. Reading the build output made this
// script depend on build ordering — and worse, let the drift check pass
// against a stale bundle, which is exactly how a real mismatch reached CI.
import {
  CONTRACT_VERSION,
  SCENE_SCHEMA_ID,
  authoringGuide,
  contractDescriptor,
  contractJsonSchema,
  guideAsMarkdown,
  guideSectionIds,
  type ContractSchemaName,
} from "../src/contract/index.js";
import { GRAMMAR_SCHEMAS } from "../src/diagrams/grammars.js";
import { SLIDE_FORMATS } from "../src/design/grid.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED_NOTICE = "<!-- Generated by scripts/generate-docs.ts from src/contract. Do not edit by hand. -->";

const SKILL_DESCRIPTION = "Invent, create, edit, revise, render, validate, and export distinctive editable PowerPoint presentations with model-authored art direction, typography, colour, composition, diagrams, charts, imagery, and slide-native elements. Use for new `.pptx` decks, existing PowerPoint edits, visual storytelling, themes or brand systems, freeform slide canvases, native charts/tables/diagrams, previews, layout QA, structured JSON requests, or any workflow that must return a production-ready PowerPoint rather than flattened screenshots.";

/**
 * A checkout on Windows carries CRLF; everything generated here uses LF.
 * Comparing the two verbatim reported every file as out of date on Windows and
 * nowhere else, so both sides are normalised before they are compared.
 */
function normalize(text: string): string {
  return text.replace(/\r\n/g, "\n");
}

function skillFrontmatter(description: string): string {
  return ["---", "name: slide-agent", `description: ${description}`, "---", ""].join("\n");
}

/**
 * Every generated file, keyed by repository-relative path. Building the whole
 * set in memory is what lets `--check` verify all of it rather than sampling
 * one file, and keeps writing and checking from drifting apart.
 */
function buildDocs(): Map<string, string> {
  const files = new Map<string, string>();

  const commands = [
    "## Commands",
    "",
    "```bash",
    "slide-agent contract --format prompt        # the full authoring guide",
    "slide-agent contract --schema outline       # JSON Schema for what you author",
    "slide-agent run --request request.json      # build from an outline or scene",
    "slide-agent create --prompt brief.md --output deck.pptx   # structural draft only",
    "slide-agent revise --input deck.pptx --slide 4 --records slide4.ndjson --output revised.pptx",
    "slide-agent validate --input deck.pptx      # geometry, schema, accessibility, quality",
    "slide-agent render --input deck.pptx --output previews/   # optional PDF/PNG",
    "slide-agent diff --before a.pptx --after b.pptx",
    "slide-agent data --input numbers.csv        # chart spec with provenance",
    "```",
    "",
    `Slide formats: ${Object.keys(SLIDE_FORMATS).map((name) => `\`${name}\``).join(", ")}.`,
    `Diagram grammars: ${Object.keys(GRAMMAR_SCHEMAS).map((name) => `\`${name}\``).join(", ")}.`,
    "",
  ].join("\n");

  files.set("SKILL.md", [
    skillFrontmatter(SKILL_DESCRIPTION),
    GENERATED_NOTICE,
    "",
    guideAsMarkdown().replace(/^# Slide Agent authoring guide\n/, "# Slide Agent\n"),
    "",
    commands,
  ].join("\n"));

  for (const section of guideSectionIds()) {
    files.set(`references/${section}.md`, `${GENERATED_NOTICE}\n\n${guideAsMarkdown(section)}`);
  }

  // The machine-readable contract, committed so it is reviewable in a diff.
  for (const name of contractDescriptor().schemas) {
    files.set(
      `references/schemas/${name}.schema.json`,
      `${JSON.stringify(contractJsonSchema(name as ContractSchemaName), null, 2)}\n`,
    );
  }

  files.set("references/README.md", [
    GENERATED_NOTICE,
    "",
    "# Reference",
    "",
    `Authoring contract ${CONTRACT_VERSION} · scene schema \`${SCENE_SCHEMA_ID}\``,
    "",
    "Every page here is generated from `src/contract`. Change the contract, run",
    "`npm run docs`, and the prose, the schemas, and the engine stay in step.",
    "",
    "## Guide",
    "",
    ...authoringGuide().sections.map((section) => `- [${section.title}](${section.id}.md) — ${section.body[0] ?? ""}`),
    "",
    "## Schemas",
    "",
    ...contractDescriptor().schemas.map((name) => `- [\`${name}\`](schemas/${name}.schema.json)`),
    "",
  ].join("\n"));

  return files;
}

async function main(): Promise<void> {
  const files = buildDocs();
  await mkdir(path.join(root, "references", "schemas"), { recursive: true });
  for (const [relative, content] of files) {
    await writeFile(path.join(root, relative), content, "utf8");
  }
  process.stdout.write(`Generated ${files.size} file(s) from the authoring contract.\n`);
}

/**
 * Fails when any committed file no longer matches what the contract produces.
 * The previous version compared 400 characters of SKILL.md, so a reference page
 * could be replaced with anything at all and the check still reported success.
 */
async function check(): Promise<void> {
  const files = buildDocs();
  const stale: string[] = [];
  for (const [relative, expected] of files) {
    const actual = await readFile(path.join(root, relative), "utf8").catch(() => undefined);
    if (actual === undefined) {
      stale.push(`${relative} (missing)`);
    } else if (normalize(actual) !== normalize(expected)) {
      stale.push(relative);
    }
  }
  if (stale.length > 0) {
    throw new Error(
      `${stale.length} generated file(s) are out of date with the authoring contract:\n`
      + `${stale.map((entry) => `  ${entry}`).join("\n")}\n`
      + "Run `npm run docs`.",
    );
  }
  process.stdout.write(`Generated documentation is in step with the contract (${files.size} files).\n`);
}

const command = process.argv[2] === "--check" ? check : main;
command().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
