#!/usr/bin/env node
// Renders SKILL.md and the reference docs from the authoring contract, so the
// prose an agent reads and the schemas the engine enforces cannot drift apart.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Imported from source, not from dist. Reading the build output made this
// script depend on build ordering — and worse, let the drift check pass
// against a stale bundle, which is exactly how a real mismatch reached CI.
import {
  CONTRACT_VERSION,
  SCENE_SCHEMA_ID,
  contractDescriptor,
  contractJsonSchema,
  guideAsMarkdown,
  guideAsRouter,
  guideSectionIds,
  guideSectionIndex,
  type ContractSchemaName,
} from "../src/contract/index.js";
import { GRAMMAR_SCHEMAS } from "../src/diagrams/grammars.js";
import { SLIDE_FORMATS } from "../src/design/grid.js";
import { GRAMMAR } from "../src/v2/commands/catalog.js";
import { RECIPES } from "../src/v2/compose/recipes.js";
import { INTENT_SCHEMA_ID } from "../src/v2/ir/intent.js";
import { presetNames } from "../src/v2/tokens/presets.js";
import { deckIntent } from "../src/v2/ir/intent.js";
import { z } from "zod";
import { SKILL_V2 } from "../src/v2/commands/skill.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED_NOTICE = "<!-- Generated by scripts/generate-docs.ts from src/contract. Do not edit by hand. -->";

const SKILL_DESCRIPTION = "Design and build editable PowerPoint decks: you direct the design — concept, palette, typography, composition, emphasis, rhythm — and the engine solves geometry, fits text, verifies contrast, and writes native .pptx with theme colours, placeholders, embedded fonts, native charts, tables, diagrams, and icons. Use for new decks, edits to existing PowerPoint, brand templates, data-driven decks at volume, previews, and layout QA — anything that must return a real .pptx rather than screenshots.";

/**
 * A checkout on Windows carries CRLF; everything generated here uses LF.
 * Comparing the two verbatim reported every file as out of date on Windows and
 * nowhere else, so both sides are normalised before they are compared.
 */
function normalize(text: string): string {
  return text.replace(/\r\n/g, "\n");
}

function skillFrontmatter(description: string): string {
  return ["---", "name: slide-agent", `description: ${description}`, "---", ""].join("\n");
}

/**
 * Every generated file, keyed by repository-relative path. Building the whole
 * set in memory is what lets `--check` verify all of it rather than sampling
 * one file, and keeps writing and checking from drifting apart.
 */
function buildDocs(): Map<string, string> {
  const files = new Map<string, string>();

  const commands = [
    "## Commands",
    "",
    "```bash",
    "slide-agent contract --format markdown --section canvas   # one guide section",
    "slide-agent contract --format prompt        # the whole guide, as a system prompt",
    "slide-agent contract --schema outline       # JSON Schema, for validators",
    "slide-agent build --script deck.mjs --output deck.pptx    # the recommended path",
    "slide-agent run --request request.json      # build from an outline or scene",
    "slide-agent create --prompt brief.md --output deck.pptx   # structural draft only",
    "slide-agent revise --input deck.pptx --slide 4 --records slide4.ndjson --output revised.pptx",
    "slide-agent validate --input deck.pptx      # geometry, schema, accessibility, quality",
    "slide-agent render --input deck.pptx --output previews/   # optional PDF/PNG",
    "slide-agent diff --before a.pptx --after b.pptx",
    "slide-agent data --input numbers.csv        # chart spec with provenance",
    "```",
    "",
    `Slide formats: ${Object.keys(SLIDE_FORMATS).map((name) => `\`${name}\``).join(", ")}.`,
    `Diagram grammars: ${Object.keys(GRAMMAR_SCHEMAS).map((name) => `\`${name}\``).join(", ")}.`,
    "",
  ].join("\n");

  // The router, not the whole guide. Inlining every section here made SKILL.md
  // a second copy of `references/` — 94% of its substantive lines appeared in
  // both — which a host with the skill and the MCP server registered paid for
  // twice, before knowing whether the deck had a chart in it.
  files.set("SKILL.md", [
    skillFrontmatter(SKILL_DESCRIPTION),
    GENERATED_NOTICE.replace("src/contract", "src/v2/commands/skill.ts"),
    "",
    SKILL_V2,
  ].join("\n"));

  // The composition language, as a page a host can read without MCP.
  files.set("references/v2/grammar.md", `${GENERATED_NOTICE.replace("src/contract", "src/v2/commands/catalog.ts")}\n\n${GRAMMAR}`);
  files.set("references/v2/recipes.md", [
    GENERATED_NOTICE.replace("src/contract", "src/v2/compose/recipes.ts"),
    "",
    "# Recipes",
    "",
    "Saved compositions with named slots: starting points for routine slides, and what draft mode and template-fill fill.",
    "`slides_view {what: \"expand\"}` returns the composition behind one so you can rework it.",
    "",
    ...RECIPES.map((recipe) => `- \`${recipe.id}\` — ${recipe.summary}. Slots: ${Object.entries(recipe.slots).map(([slot, spec]) => typeof spec === "string" ? `\`${slot}${spec.endsWith("?") ? "?" : ""}\`` : `\`${slot}[${spec.min}–${spec.max}]\``).join(", ")}.`),
    "",
    `Presets (draft themes, always labelled): ${presetNames().map((name) => `\`${name}\``).join(", ")}.`,
    "",
  ].join("\n"));
  files.set("references/v2/intent.schema.json", `${JSON.stringify(z.toJSONSchema(deckIntent, { io: "input", unrepresentable: "any" }), null, 2)}\n`);

  // V1's router stays available for decks still authored against 0.x.
  files.set("references/v1-skill.md", [
    GENERATED_NOTICE,
    "",
    `# Slide Agent 0.x authoring (compatibility)\n`,
    `The 0.x canvas contract, for decks authored before ${INTENT_SCHEMA_ID}. New work should use the V2 grammar in [v2/grammar.md](v2/grammar.md).\n`,
    guideAsRouter(),
    "",
    commands,
  ].join("\n"));

  // The whole guide stays available as one page for hosts that want it, and
  // for anyone reading the contract end to end.
  files.set("references/guide.md", `${GENERATED_NOTICE}\n\n${guideAsMarkdown()}`);

  for (const section of guideSectionIds()) {
    files.set(`references/${section}.md`, `${GENERATED_NOTICE}\n\n${guideAsMarkdown(section)}`);
  }

  // The machine-readable contract, committed so it is reviewable in a diff.
  for (const name of contractDescriptor().schemas) {
    files.set(
      `references/schemas/${name}.schema.json`,
      `${JSON.stringify(contractJsonSchema(name as ContractSchemaName), null, 2)}\n`,
    );
  }

  files.set("references/README.md", [
    GENERATED_NOTICE,
    "",
    "# Reference",
    "",
    "## 2.x — the composition language",
    "",
    "The default authoring format. The model writes a `slide-agent.intent/1`",
    "document in grid units, roles, and tokens; the engine computes the rest.",
    "",
    "- [Composition grammar](v2/grammar.md) — the language, with worked examples. Read this one.",
    "- [Recipes and presets](v2/recipes.md) — labelled starting points for routine slides",
    "- [`slide-agent.intent/1` JSON Schema](v2/intent.schema.json) — for validators and structured output",
    "",
    "---",
    "",
    "## 0.x — the canvas contract",
    "",
    `Authoring contract ${CONTRACT_VERSION} · scene schema \`${SCENE_SCHEMA_ID}\``,
    "",
    "Still supported: scenes, outlines, and build scripts build unchanged, and",
    "`canvas` slides are a first-class 2.x slide kind. [`v1-skill.md`](v1-skill.md)",
    "is the router for this contract, and `slide-agent migrate` converts a scene",
    "or outline into an intent.",
    "",
    "Every page below is generated from `src/contract`. Change the contract, run",
    "`npm run docs`, and the prose, the schemas, and the engine stay in step.",
    "",
    "Read a section when its moment arrives rather than all of them up front.",
    "The whole guide as one page is [`guide.md`](guide.md).",
    "",
    "### Guide",
    "",
    ...guideSectionIndex().map((section) => `- [${section.title}](${section.id}.md) — ${section.when} (~${section.approximateTokens} tokens)`),
    "",
    "### Schemas",
    "",
    ...contractDescriptor().schemas.map((name) => `- [\`${name}\`](schemas/${name}.schema.json)`),
    "",
  ].join("\n"));

  return files;
}

async function main(): Promise<void> {
  const files = buildDocs();
  await mkdir(path.join(root, "references", "schemas"), { recursive: true });
  await mkdir(path.join(root, "references", "v2"), { recursive: true });
  for (const [relative, content] of files) {
    await writeFile(path.join(root, relative), content, "utf8");
  }
  process.stdout.write(`Generated ${files.size} file(s) from the authoring contract.\n`);
}

/**
 * Fails when any committed file no longer matches what the contract produces.
 * The previous version compared 400 characters of SKILL.md, so a reference page
 * could be replaced with anything at all and the check still reported success.
 */
async function check(): Promise<void> {
  const files = buildDocs();
  const stale: string[] = [];
  for (const [relative, expected] of files) {
    const actual = await readFile(path.join(root, relative), "utf8").catch(() => undefined);
    if (actual === undefined) {
      stale.push(`${relative} (missing)`);
    } else if (normalize(actual) !== normalize(expected)) {
      stale.push(relative);
    }
  }
  if (stale.length > 0) {
    throw new Error(
      `${stale.length} generated file(s) are out of date with the authoring contract:\n`
      + `${stale.map((entry) => `  ${entry}`).join("\n")}\n`
      + "Run `npm run docs`.",
    );
  }
  process.stdout.write(`Generated documentation is in step with the contract (${files.size} files).\n`);
}

const command = process.argv[2] === "--check" ? check : main;
command().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
