#!/usr/bin/env node
// Renders SKILL.md and the reference docs from the authoring contract, so the
// prose an agent reads and the schemas the engine enforces cannot drift apart.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED_NOTICE = "<!-- Generated by scripts/generate-docs.mjs from src/contract. Do not edit by hand. -->";

async function contract() {
  return import(pathToFileURL(path.join(root, "dist", "index.js")).href);
}

function skillFrontmatter(description) {
  return ["---", "name: slide-agent", `description: ${description}`, "---", ""].join("\n");
}

const SKILL_DESCRIPTION = "Invent, create, edit, revise, render, validate, and export distinctive editable PowerPoint presentations with model-authored art direction, typography, colour, composition, diagrams, charts, imagery, and slide-native elements. Use for new `.pptx` decks, existing PowerPoint edits, visual storytelling, themes or brand systems, freeform slide canvases, native charts/tables/diagrams, previews, layout QA, structured JSON requests, or any workflow that must return a production-ready PowerPoint rather than flattened screenshots.";

async function main() {
  const {
    CONTRACT_VERSION,
    SCENE_SCHEMA_ID,
    authoringGuide,
    contractDescriptor,
    contractJsonSchema,
    guideAsMarkdown,
    guideSectionIds,
    GRAMMAR_SCHEMAS,
    SLIDE_FORMATS,
  } = await contract();

  const written = [];

  // SKILL.md: frontmatter plus the guide, plus the commands an agent runs.
  const commands = [
    "## Commands",
    "",
    "```bash",
    "slide-agent contract --format prompt        # the full authoring guide",
    "slide-agent contract --schema outline       # JSON Schema for what you author",
    "slide-agent run --request request.json      # build from an outline or scene",
    "slide-agent create --prompt brief.md --output deck.pptx   # structural draft only",
    "slide-agent revise --input deck.pptx --slide 4 --records slide4.ndjson --output revised.pptx",
    "slide-agent validate --input deck.pptx      # geometry, schema, accessibility, quality",
    "slide-agent render --input deck.pptx --output previews/   # optional PDF/PNG",
    "slide-agent diff --before a.pptx --after b.pptx",
    "slide-agent data --input numbers.csv        # chart spec with provenance",
    "```",
    "",
    `Slide formats: ${Object.keys(SLIDE_FORMATS).map((name) => `\`${name}\``).join(", ")}.`,
    `Diagram grammars: ${Object.keys(GRAMMAR_SCHEMAS).map((name) => `\`${name}\``).join(", ")}.`,
    "",
  ].join("\n");

  const skill = [
    skillFrontmatter(SKILL_DESCRIPTION),
    GENERATED_NOTICE,
    "",
    guideAsMarkdown().replace(/^# Slide Agent authoring guide\n/, "# Slide Agent\n"),
    "",
    commands,
  ].join("\n");
  await writeFile(path.join(root, "SKILL.md"), skill, "utf8");
  written.push("SKILL.md");

  // One reference page per guide section.
  const referenceDir = path.join(root, "references");
  await mkdir(referenceDir, { recursive: true });
  for (const section of guideSectionIds()) {
    const file = path.join(referenceDir, `${section}.md`);
    await writeFile(file, `${GENERATED_NOTICE}\n\n${guideAsMarkdown(section)}`, "utf8");
    written.push(path.relative(root, file));
  }

  // The machine-readable contract, committed so it is reviewable in a diff.
  const schemaDir = path.join(root, "references", "schemas");
  await mkdir(schemaDir, { recursive: true });
  for (const name of contractDescriptor().schemas) {
    const file = path.join(schemaDir, `${name}.schema.json`);
    await writeFile(file, `${JSON.stringify(contractJsonSchema(name), null, 2)}\n`, "utf8");
    written.push(path.relative(root, file));
  }

  const index = [
    GENERATED_NOTICE,
    "",
    "# Reference",
    "",
    `Authoring contract ${CONTRACT_VERSION} · scene schema \`${SCENE_SCHEMA_ID}\``,
    "",
    "Every page here is generated from `src/contract`. Change the contract, run",
    "`npm run docs`, and the prose, the schemas, and the engine stay in step.",
    "",
    "## Guide",
    "",
    ...authoringGuide().sections.map((section) => `- [${section.title}](${section.id}.md) — ${section.body[0] ?? ""}`),
    "",
    "## Schemas",
    "",
    ...contractDescriptor().schemas.map((name) => `- [\`${name}\`](schemas/${name}.schema.json)`),
    "",
  ].join("\n");
  await writeFile(path.join(referenceDir, "README.md"), index, "utf8");
  written.push("references/README.md");

  process.stdout.write(`Generated ${written.length} file(s) from the authoring contract.\n`);
}

/** Fails when the committed docs no longer match the contract. */
async function check() {
  const { guideAsMarkdown } = await contract();
  const skill = await readFile(path.join(root, "SKILL.md"), "utf8").catch(() => "");
  const expected = guideAsMarkdown().split("\n").slice(4).join("\n").trim();
  if (!skill.includes(expected.slice(0, 400))) {
    throw new Error("SKILL.md is out of date with the authoring contract. Run `npm run docs`.");
  }
  process.stdout.write("Generated documentation is in step with the contract.\n");
}

const command = process.argv[2] === "--check" ? check : main;
command().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
