/** Nominal content for every slot shape. */
export const SAMPLE: Record<string, unknown> = {
  title: "Pilot first cuts rollout risk in half",
  subtitle: "A six-gate plan for the steering committee",
  kicker: "Board decision",
  date: "September 2026",
  number: "02",
  lead: "What changes for each business unit",
  statement: "Pilot first, in Finance, starting October",
  support: "One unit absorbs the learning before everyone else",
  points: ["Fails small, in one unit", "Six weeks longer than big-bang", "Keeps legacy paths until wave two"],
  items: [{ label: "Why now", detail: "Audit findings" }, { label: "The plan", detail: "Six gates" }, { label: "The ask", detail: "Budget" }],
  groups: [{ name: "Big-bang", points: ["Fastest on paper", "One failure stops everyone"], verdict: "Rejected" }, { name: "Pilot first", points: ["Fails small", "Six weeks longer"], verdict: "Recommended" }],
  metrics: [{ value: "−41%", label: "Churn", note: "two quarters" }, { value: "$4.2M", label: "ARR" }, { value: "18k", label: "Users" }],
  hero: { value: "−71%", label: "Lateral movement in pilot units" },
  chart: { categories: ["Q1", "Q2", "Q3", "Q4"], series: [{ name: "Incidents", values: [42, 37, 21, 12] }] },
  takeaways: ["Incidents fell every quarter", "The drop began with the pilot"],
  takeaway: "The pilot paid for itself in two quarters",
  source: "Security operations, 2026",
  table: { columns: ["Risk", "Likelihood", "Mitigation"], rows: [["Legacy auth", "High", "Wave two"], ["Staff time", "Medium", "Backfill"]] },
  events: [{ date: "Oct", label: "Pilot", detail: "Finance" }, { date: "Jan", label: "Wave one" }, { date: "Apr", label: "Wave two" }],
  steps: [{ label: "Inventory", detail: "What talks to what" }, { label: "Identity" }, { label: "Policy" }, { label: "Pilot" }],
  nodes: [{ id: "a", label: "Users" }, { id: "b", label: "Gateway" }, { id: "c", label: "Services" }],
  edges: [{ from: "a", to: "b" }, { from: "b", to: "c" }],
  quadrants: [{ name: "Quick wins" }, { name: "Big bets" }, { name: "Fill-ins" }, { name: "Money pits" }],
  image: { asset: "poppler-slide.png", alt: "A rendered slide" },
  quote: "We found out in one unit instead of in all of them.",
  attribution: "CISO",
  people: [{ name: "Ada", role: "Lead" }, { name: "Grace", role: "Engineering" }],
  challenge: "Flat network", solution: "Pilot-first zero trust", result: "Incidents down 71%",
  before: "Every unit exposed at once", after: "One unit learns first",
  pairs: [{ q: "Why not big-bang?", a: "One failure stops everyone." }],
  sources: ["Security operations report, 2026", "Vendor benchmark"],
  actions: ["Approve the pilot", "Name the Finance sponsor"],
  contact: "security@example.com",
  ask: "Approve €1.4M",
  body: "One business unit learns first.",
};
